favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://brewed8.local/themes/main/bootstrap/favicon.ico'
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: ''
  url: ''
  use_default: true
schemas:
  bootstrap: 8000
  brewed_theme: 8000
